import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { z } from "zod";
import { Mail, MapPin, Phone, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro } from "@/components/hotel/site-shell";
import { submitContact } from "@/lib/hotel-submissions.functions";
const schema = z.object({ name: z.string().trim().min(2, "Please enter your name.").max(100), email: z.string().trim().email("Please enter a valid email address.").max(255), subject: z.string().trim().min(2, "Please add a subject.").max(120), message: z.string().trim().min(10, "Please write at least 10 characters.").max(1000) });
export const Route = createFileRoute("/contact")({ head: () => ({ meta: [{ title: "Contact | Royal Crest Hotel" }, { name: "description", content: "Get in touch with Royal Crest Hotel. Send a question about rooms, dining, or your upcoming stay." }, { property: "og:title", content: "Contact | Royal Crest Hotel" }, { property: "og:description", content: "Have a question about your stay? Get in touch with Royal Crest Hotel." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ContactPage });
export function ContactSection({ embedded = false }: { embedded?: boolean }) {
 const [error,setError] = useState(""); const [sent,setSent] = useState(false); const [busy,setBusy] = useState(false);
 async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); setSent(false); const form = e.currentTarget; const result = schema.safeParse(Object.fromEntries(new FormData(form).entries())); if (!result.success) { setError(result.error.issues[0]?.message ?? "Please check your message."); return; } setBusy(true); try { await submitContact({ data: result.data }); setSent(true); form.reset(); } catch (err) { setError(err instanceof Error ? err.message : "Could not save your message."); } finally { setBusy(false); } }
 return <>{!embedded && <PageIntro eyebrow="WE'D LOVE TO HEAR FROM YOU" title="Get in Touch" text="Questions, special requests, or just saying hello? We're always happy to hear from you."/>}<section id={embedded ? "contact" : undefined} className="section-band"><div className="container form-layout"><div className="form-panel"><h2>Send a message</h2><p>Leave us a note and see your message preview.</p><form onSubmit={submit} noValidate><div className="form-grid"><div className="form-field"><label htmlFor="contact-name">Your name</label><input id="contact-name" name="name" placeholder="Your full name" autoComplete="name" maxLength={100} required/></div><div className="form-field"><label htmlFor="contact-email">Email address</label><input id="contact-email" name="email" type="email" placeholder="you@example.com" autoComplete="email" maxLength={255} required/></div><div className="form-field full"><label htmlFor="subject">Subject</label><input id="subject" name="subject" placeholder="How can we help?" maxLength={120} required/></div><div className="form-field full"><label htmlFor="message">Your message</label><textarea id="message" name="message" placeholder="Tell us what's on your mind..." maxLength={1000} required/></div></div>{error && <p role="alert" className="form-error">{error}</p>}<Button variant="gold" className="form-submit" type="submit" disabled={busy}>{busy ? "Saving message..." : "Send Message"} <ArrowUpRight size={16}/></Button><p className="form-note">Your message is securely saved for the hotel team to review.</p></form>{sent && <div role="status" className="form-success"><strong>Message received.</strong>Your message has been saved.</div>}</div><aside className="info-panel"><h3>We're here for you</h3><p>We would be delighted to help you plan your next visit.</p><div className="info-item"><Phone size={21}/><div><strong>Phone</strong><span>Contact details available on request</span></div></div><div className="info-item"><Mail size={21}/><div><strong>Email</strong><span>Contact details available on request</span></div></div><div className="info-item"><MapPin size={21}/><div><strong>Address</strong><span>24 Heritage Boulevard<br/>Central District, New Delhi<br/>Illustrative address for this demo</span></div></div><Link to="/location" className="text-action">Explore location <ArrowUpRight size={16}/></Link></aside></div></section></>;
}

function ContactPage() { return <ContactSection/>; }
