/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as LocationRouteImport } from './routes/location'
import { Route as RoomsRouteImport } from './routes/rooms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/location': typeof LocationRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/location': typeof LocationRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/facilities': typeof FacilitiesRoute
  '/location': typeof LocationRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/location'
    | '/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/location'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/dining'
    | '/facilities'
    | '/location'
    | '/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  FacilitiesRoute: typeof FacilitiesRoute
  LocationRoute: typeof LocationRoute
  RoomsRoute: typeof RoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  FacilitiesRoute: FacilitiesRoute,
  LocationRoute: LocationRoute,
  RoomsRoute: RoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
